# Generated by Django 4.2.3 on 2023-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_applicant_is_verified_company_is_verified_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
