# Generated by Django 4.2.3 on 2023-09-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_applicant_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
