# Generated by Django 4.2.3 on 2023-09-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applicant_details', 'Applicant Details'), ('job_scheduling', 'Job Scheduling')], default=False, max_length=20),
        ),
    ]
